name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nixbuild:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: nixbuild/nix-quick-install-action@v21
      - uses: nixbuild/nixbuild-action@v15
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
          generate-summary-for: 'workflow'
      - run: nix-build
